'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Inforum_Consolidador.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT T0.&quot;ACCOUNTCODE&quot;,
        '''      CASE WHEN T1.&quot;GroupMask&quot; IN (2,3,4,7) AND T0.&quot;CREDIT&quot; &lt; 0
        '''            THEN - T0.&quot;CREDIT&quot;
        '''            WHEN T1.&quot;GroupMask&quot; IN (1,5,6,8) AND T0.&quot;DEBIT&quot; &lt; 0
        '''            THEN 0.00            
        '''            ELSE T0.&quot;DEBIT&quot;       
        '''      END DEBIT,     
        '''      CASE WHEN T1.&quot;GroupMask&quot; IN (1,5,6,8) AND T0.&quot;DEBIT&quot; &lt; 0
        '''            THEN - T0.&quot;DEBIT&quot;
        '''            WHEN T1.&quot;GroupMask&quot; IN (2,3,4,7) AND T0.&quot;CREDIT&quot; &lt; 0
        '''            THEN 0.00
        '''            ELSE T0.&quot;CREDIT&quot;
        '''END CREDIT,
        '''CAS [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQL_Consolida() As String
            Get
                Return ResourceManager.GetString("SQL_Consolida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT DISTINCT(T0.&quot;BRANCH&quot;) AS BRANCH      
        '''FROM
        '''(
        '''SELECT  
        '''      T1.&quot;FormatCode&quot; ACCOUNTCODE,
        '''      CASE WHEN T1.&quot;GroupMask&quot; IN (2,3,4,7)
        '''            THEN ROUND(SUM(IFNULL(T0.&quot;Credit&quot;,0) - IFNULL(T0.&quot;Debit&quot;,0)),2)
        '''            ELSE 0
        '''            END CREDIT,
        '''       CASE WHEN T1.&quot;GroupMask&quot; IN (2,3,4,7)
        '''            THEN ROUND(SUM(IFNULL(T0.&quot;SYSCred&quot;,0) - IFNULL(T0.&quot;SYSDeb&quot;,0)),2)
        '''            ELSE 0
        '''            END &quot;CREDITMS&quot;,
        '''      CASE WHEN T1.&quot;GroupMask&quot; IN (1,5,6,8)
        '''            THEN ROUND(SU [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQL_Consolida_Branches() As String
            Get
                Return ResourceManager.GetString("SQL_Consolida_Branches", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
